config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  # Long version
  # get '/pages', to: 'pages#index'
  # get '/pages/:id', to: 'pages#show'
  # post '/pages', to: 'pages#create'
  # put '/pages/:id', to: 'pages#update'
  # delete '/pages/:id', to 'pages#destroy'

  # Short version of above
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # All Blog Pages
    @pages = Page.all
  end

  def show
    # Finding a page by id from the db and giving the view access
    @page = Page.find(params[:id])
  end

  def edit
    # Shows a pre-filled form to edit the page
  end

  def update
    # Take data from the form and update the page in our database
  end

  def new
    # Shows a blank form to create a new page
    @page = Page.new
  end

  def create
    # Take data from the form and create a new page in our database
    @page = Page.new(title: params[:page][:title],
                      author: params[:page][:author],
                      content: params[:page][:content],
                      public: params[:page][:public])
    if @page.save
      # success
      redirect_to pages_path
    else
      # fail
      render :new
    end
  end

  def destroy
    # Finds the page by ID and removes it from the database
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb<p>

app/views/pages/index.html.erb
<h1>Pages</h1>

<% if @pages.any? %>

  <% @pages.each do |page| %>
    <h3>
      <%= link_to page.title, page_path(page) %>
    </h3>
  <% end %>

<% else %>

  <h4>No Pages, Please Create One!</h4>

<% end %>

<!-- <a href='/pages/new'>New Blog Post</a> -->
<%= link_to 'New Blog Post', new_page_path %>

app/views/pages/new.html.erb
<h1>New Blog Post</h1>

<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, required: true %>
  <br />
  <%= f.label :content %>
  <%= f.text_area :content, required: true %>
  <br />
  <%= f.label :public %>
  <%= f.check_box :public %>
  <br />
  <%= f.submit %>
<% end %>

<%= link_to 'All Posts', pages_path, class: 'btn btn-primary' %>

app/views/pages/show.html.erb
<h1>
  <%= @page.title %>
</h1>

<hr />